services:
  airflow-tutorial:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-tutorial
    container_name: airflow-tutorial
    ports:
      - "8080:8080"   # Airflow webserver
      - "8888:8888"   # Jupyter Lab
    volumes:
      - ./airflow/dags:/home/airflow/dags
    environment:
      AIRFLOW__WEBSERVER__BASE_URL: "${AIRFLOW_BASE_URL:-http://localhost:8080}"
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
      AIRFLOW__CORE__INTERNAL_API_URL: "http://localhost:8080"
